INSERT INTO Arena VALUES ('State Farm Arena', 18729);
INSERT INTO Arena VALUES ('TD Garden', 18624);
INSERT INTO Arena VALUES ('Smoothie King Center', 17791);
INSERT INTO Arena VALUES ('United Center', 21711);
INSERT INTO Arena VALUES ('American Airlines Center', 19200);
INSERT INTO Arena VALUES ('Pepsi Center', 19099);
INSERT INTO Arena VALUES ('Toyota Center', 18104);
INSERT INTO Arena VALUES ('Staples Center', 19060);
INSERT INTO Arena VALUES ('AmericanAirlines Arena', 19600);
INSERT INTO Arena VALUES ('Fiserv Forum', 17500);
INSERT INTO Arena VALUES ('Target Center', 19356);
INSERT INTO Arena VALUES ('Barclays Center', 19000);
INSERT INTO Arena VALUES ('Madison Square Garden', 19763);
INSERT INTO Arena VALUES ('Amway Center',  18500);
INSERT INTO Arena VALUES ('Bankers Life Fieldhouse', 18345);
INSERT INTO Arena VALUES ('Wells Fargo Center', 21000);
INSERT INTO Arena VALUES ('Talking Stick Resort Arena', 18000);
INSERT INTO Arena VALUES ('Moda Center', 19980);
INSERT INTO Arena VALUES ('Golden 1 Center', 17500);
INSERT INTO Arena VALUES ('AT&T Center', 18694);
INSERT INTO Arena VALUES ('Chesapeake Energy Arena', 19163);
INSERT INTO Arena VALUES ('Scotiabank Arena', 19800);
INSERT INTO Arena VALUES ('Vivint Smart Home Arena', 20148);
INSERT INTO Arena VALUES ('FedExForum', 18119);
INSERT INTO Arena VALUES ('Capital One Arena', 20647);
INSERT INTO Arena VALUES ('Little Caesars Arena', 21000);
INSERT INTO Arena VALUES ('Spectrum Center', 19026);
INSERT INTO Arena VALUES ('Quicken Loans Arena', 20562);
INSERT INTO Arena VALUES ('Chase Center', 19596);